apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-stillingsregistrering-api
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /isalive
    initialDelay: 40
    timeout: 60
  readiness:
    path: /isready
    initialDelay: 40
    timeout: 60
  replicas:
    min: 1
    max: 1
  strategy:
    type: Recreate
  prometheus:
    enabled: true
    path: /actuator/prometheus
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 512Mi
  ingresses: 
    {{#each ingresses as |url|}}
      - {{url}}
    {{/each}}
  gcp:
    sqlInstances:
    - type: POSTGRES_12
      databases:
        - name: pam-stillingsregistrering-api
          envVarPrefix: PAMADREGDB
