spring:
  application:
    name: pam-stillingsregistrering-api-migration
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://${PAMADREGDB_HOST}:${PAMADREGDB_PORT}/${PAMADREGDB_DATABASE}
    username: ${PAMADREGDB_USERNAME}
    password: ${PAMADREGDB_PASSWORD}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 4

management:
  endpoints:
    web:
      exposure:
        include: ["prometheus"]
